### ISSUE TITLE
Downloading problem?

### ISSUE THREAD

**Issue by abcdvzz** [jiangtaoxie/fast-MPN-COV#10]
When I ran the code finetune.sh, it began to download from jtxie.com while it's too slow. So I decided to use BaiduYun. However,  I got the following problem:

`Start finetuning!
Namespace(arch='mpncovresnet101', batch_size=10, benchmark='CUB', classifier_factor=5, data='/path/to/the/data/CUB', dist_backend='gloo', dist_url='tcp://224.66.41.62:23456', epochs=100, evaluate=False, freezed_layer=0, gpu=1, lr=0.0012, lr_method='step', lr_params=[[100.0]], modeldir='Results/Finetune-CUB-mpncovresnet101-MPNCOV-reproduce-lr1.2e-3-bs10', momentum=0.9, num_classes=200, pretrained=True, print_freq=100, representation='MPNCOV', resume='Results/Finetune-CUB-mpncovresnet101-MPNCOV-reproduce-lr1.2e-3-bs10/mpncovresnet101-ade9737a.pth.tar', seed=None, start_epoch=0, store_model_everyepoch=False, weight_decay=0.0001, workers=8, world_size=1)
main.py:127: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
=> loading checkpoint 'Results/Finetune-CUB-mpncovresnet101-MPNCOV-reproduce-lr1.2e-3-bs10/mpncovresnet101-ade9737a.pth.tar'
Traceback (most recent call last):
  File "main.py", line 503, in <module>
    main()
  File "main.py", line 206, in main
    checkpoint = torch.load(args.resume)
  File "/home/yzzc/.local/lib/python3.5/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/yzzc/.local/lib/python3.5/site-packages/torch/serialization.py", line 527, in _load
    return legacy_load(f)
  File "/home/yzzc/.local/lib/python3.5/site-packages/torch/serialization.py", line 441, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/usr/lib/python3.5/tarfile.py", line 2027, in extract
    tarinfo = self.getmember(member)
  File "/usr/lib/python3.5/tarfile.py", line 1738, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"
`
How can I solve this problem?

**Comment by abcdvzz** [comment]
The mpnconvresnet50-15991845.pth is ok but resnet101 one still has the problem.

**Comment by jiangtaoxie** [comment]
`mpncovresnet101-ade9737a.pth` is not checkpoint file. Please put the model into `~/.torch/models/` and try it again.

**Comment by abcdvzz** [comment]
> `mpncovresnet101-ade9737a.pth` is not checkpoint file. Please put the model into `~/.torch/models/` and try it again.

I did so. I did the same operation to resnet50 model and it worked. But it is not fit for the resnet101 one.

**Comment by jiangtaoxie** [comment]
@abcdvzz I didn't reproduce this problem. I uploaded a new [model](https://pan.baidu.com/s/1vK6VZK239lHBh22C7IihZw), you can try it, code: rurg
Please fell free if you want to reopen this issue.

**Comment by OrkhanHI** [comment]
I am unable to download *mpncovresnet50-15991845.pth* from http://jtxie.com/models/mpncovresnet50-15991845.pth because the web-site does not work. 

Is anybody able to send me that pth file?

**Comment by jiangtaoxie** [comment]
@OrkhanHI Hi, you can download it in this path [Google Drive](https://drive.google.com/open?id=1h4JCWY9WfvFzNvwh2SOQwBOVVYpODuxg)

**Comment by OrkhanHI** [comment]
@jiangtaoxie thank you!

**Comment by hturki** [comment]
Is there anywhere we can get mpncovresnet101-ade9737a.pth that's not from baidu? I'm having difficulties creating an account from overseas. Thank you!
