### ISSUE TITLE
CUB-200-20122数据集实验

### ISSUE THREAD

**Issue by zyyhl** [jiangtaoxie/fast-MPN-COV#11]
你好，我看了您的论文，发现您在CUB数据集上做了实验，您可以公布下关于这个数据集的代码吗，谢谢！

**Comment by jiangtaoxie** [comment]
https://github.com/jiangtaoxie/fast-MPN-COV/tree/master/finetune

**Comment by zyyhl** [comment]
@jiangtaoxie 谢谢您解答我的疑惑，我没有找到关于CUB数据集预处理的代码，数据应该制作的格式是什么呢？谢谢！我发现main.py文件里面直接加载imageNet数据集，我运行的是finetune.sh文件。
