### ISSUE TITLE
what are suggested training parameters for CUB_200_2001?

### ISSUE THREAD

**Issue by wjtan99** [jiangtaoxie/fast-MPN-COV#16]
I tried lr=0.1,0.01, 0.001, batch=16, after about 10 epochs, it runs into significant over fitting.  what are suggested training parameters for CUB_200_2001 to achieve top1 acc = 0.88? 
Thanks a lot.

**Comment by wjtan99** [comment]
BTW, I started new training, not fine tuning from your model.

**Comment by jiangtaoxie** [comment]
@wjtan99 I have no idea about achieving top1 acc = 0.88 when train a model from scratch on CUB. The #sample of  CUB is too small to fit model with billions of parameters.

**Comment by wjtan99** [comment]
@jiangtaoxie Hi, I of course still started from Imagenet pretrained model.  Then how did you get acc=0.88 on CUB_200_2001? 
Thanks.

**Comment by wjtan99** [comment]
I got it wrong. The script trainingFromScratch is really training from scratch without loading pre-trained model.  I switched to use finetune.sh and load VGG16_BN, now the results look much better.  
Thanks for your nice work.
