### ISSUE TITLE
Heavy training 44 batches, training acc is close to 100%, test acc is only 50%

### ISSUE THREAD

**Issue by disign-ming** [jiangtaoxie/fast-MPN-COV#18]
Epoch: [41][0/375]	Time 0.975 (0.975)	Data 0.517 (0.517)	Loss 0.0067 (0.0067)	Prec@1 100.000 (100.000)	Prec@5 100.000 (100.000)
Epoch: [41][100/375]	Time 0.707 (0.709)	Data 0.000 (0.008)	Loss 0.0183 (0.0118)	Prec@1 100.000 (100.000)	Prec@5 100.000 (100.000)
Epoch: [41][200/375]	Time 0.705 (0.708)	Data 0.000 (0.005)	Loss 0.0109 (0.0116)	Prec@1 100.000 (100.000)	Prec@5 100.000 (100.000)
Epoch: [41][300/375]	Time 0.704 (0.708)	Data 0.000 (0.005)	Loss 0.0116 (0.0122)	Prec@1 100.000 (100.000)	Prec@5 100.000 (100.000)
Test: [0/363]	Time 0.632 (0.632)	Loss 1.9474 (1.9474)	Prec@1 50.000 (50.000)	Prec@5 50.000 (68.750)
Test: [100/363]	Time 0.222 (0.227)	Loss 2.6090 (2.1146)	Prec@1 50.000 (56.064)	Prec@5 50.000 (79.517)
Test: [200/363]	Time 0.221 (0.225)	Loss 1.7332 (2.1782)	Prec@1 56.250 (54.975)	Prec@5 56.250 (78.794)
Test: [300/363]	Time 0.222 (0.224)	Loss 2.4831 (2.1763)	Prec@1 43.750 (54.464)	Prec@5 43.750 (78.675)
 * Prec@1 55.161 Prec@5 78.961

**Comment by jiangtaoxie** [comment]
Please use `finetune/finetune.sh` to reproduce. :)
