### ISSUE TITLE
When would you release the TensorFlow Implemention?

### ISSUE THREAD

**Issue by guyibang** [jiangtaoxie/fast-MPN-COV#2]

**Comment by i4yyds** [comment]
Expect the tensorflow interface

**Comment by jiangtaoxie** [comment]
@guyibang @SoulCoderCN Hi all, we have implemented the TensorFlow version of our fast MPN-COV, but the code is not evaluated for reproducing the results as reported in our paper. We'll finish it as soon as possible. :)

**Comment by WeitaoVan** [comment]
@jiangtaoxie Hi, 
May I ask if the Tensorflow implementation is ready ? I believe it will help many researchers who are following your great work. Thanks.

**Comment by jiangtaoxie** [comment]
@WeitaoVan Thanks for your attention to our work! There are some problems in our current Tensorflow implementation, which cannot reproduce the results as our paper reported. As such, we are not ready to release Tensorflow version until it works fine.

**Comment by jiangtaoxie** [comment]
TensorFlow implementation (https://github.com/XuChunqiao/Tensorflow-Fast-MPNCOV)
