### ISSUE TITLE
模型参数下载

### ISSUE THREAD

**Issue by jinshistd** [jiangtaoxie/fast-MPN-COV#27]
作者取消了模型参数下载，请问可以发一份给我吗？万分感谢。邮箱地址：jinshi.std@gmail.com

**Comment by jiangtaoxie** [comment]
![image](https://user-images.githubusercontent.com/28640449/125484526-6cededf1-3384-4205-b1ca-8643fdca8590.png)

**Comment by jinshistd** [comment]
对不起，由于我没有仔细看，又因为急于查看你们的优秀的模型导致了这个错误。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangtaoxie/fast-MPN-COV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiangtaoxie/fast-MPN-COV] 模型参数下载 (#27)





 
Closed #27.

**Comment by jinshistd** [comment]
十分感谢您的指出。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangtaoxie/fast-MPN-COV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiangtaoxie/fast-MPN-COV] 模型参数下载 (#27)





 
Closed #27.
