### ISSUE TITLE
what's the meaning of Implementations?

### ISSUE THREAD

**Issue by Deeplearning20** [jiangtaoxie/fast-MPN-COV#3]
Hello, I don't know what the meaning of three points in Implementations.
 1. Is the experiment implemented in three ways, in pytorch or tensorflow or MatConvNet? 
2. Or   use pytorch first?   then tensorflow? and finally MatConvNet? 
3.Or   use MatConvNet in the pytorch environment  (or use MatConvNet in the tensorflow environment)?
My question may be naive .Thanks very much if can hear from you.
![image](https://user-images.githubusercontent.com/39185624/49270691-75ec4600-f4a5-11e8-8e98-ec0869e726a0.png)

**Comment by jiangtaoxie** [comment]
@Deeplearning20 Hi, there may be some misunderstandings here. The three implementations we provide are independent of each other. For example, if you are a PyTorch user, you can ignore the others and only care about the contents of the `PyTorch/` folder.

**Comment by Deeplearning20** [comment]
I understand that!Thanks very much!
