### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DataParallel:

### ISSUE THREAD

**Issue by ray-lee-94** [jiangtaoxie/fast-MPN-COV#5]
When I fine-tuned the mpncovresnet50 in second stage, the error occured.
----------------------------------------------------------------------------------------------------------------
 loading checkpoint 'Finetune-c9-mpncovresnet50-MPNCOV-reproduce-lr0.001-bs40/checkpoint.pth.tar'
Traceback (most recent call last):
  File "main.py", line 436, in <module>
    main()
  File "main.py", line 179, in main
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/wen/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.representation.conv_dr_block.0.weight", "module.representation.conv_dr_block.1.weight", "module.representation.conv_dr_block.1.bias", "module.representation.conv_dr_block.1.running_mean", "module.representation.conv_dr_block.1.running_var". 
        Unexpected key(s) in state_dict: "module.features.8.weight", "module.features.9.weight", "module.features.9.bias", "module.features.9.running_mean", "module.features.9.running_var", "module.features.9.num_batches_tracked". 

[two_stage_finetune.txt](https://github.com/jiangtaoxie/fast-MPN-COV/files/2771937/two_stage_finetune.txt)
this is my config.

**Comment by VCBE123** [comment]
I delete the "--pretrained".

**Comment by ray-lee-94** [comment]
I delete the "--pretrained" on the popurse to reduce the dimension to 256. Because my dataset is small.

**Comment by jiangtaoxie** [comment]
Hi, @VCBE123  That's right, if you delete the "--pretrained" in second stage, it'll get a different base model.

**Comment by ray-lee-94** [comment]
If i want to use the pretrained weight of resnet, But i alse need the dimension reduce.What should i do?

**Comment by jiangtaoxie** [comment]
@VCBE123 
Do you want to use dimension reduction + global averge pooling?  
if so, you can modify the `src/representation/GAvP.py` to add a dimension reduction block like `MPNCOV.py` does. Then choose `image_representation=GAvP` in shell.
if not, you can remove the condition part in [this line of main.py](https://github.com/jiangtaoxie/fast-MPN-COV/blob/master/main.py#L118)
