### ISSUE TITLE
Fatal IO error: client killed

### ISSUE THREAD

**Issue by txiaoyun** [jiangtaoxie/fast-MPN-COV#6]
When I run the code, the following errors occur: Fatal IO error: client killed, and terminate the program.  Is it the problem of my system environment? Do you know how to solve it? Thanks very much!

This error will only occur when I run the second time, and the first time it runs successfully.

**Comment by jiangtaoxie** [comment]
@txiaoyun Can you post your environment details and command lines in terminal ? I have not met this problem, maybe others can help you.

**Comment by txiaoyun** [comment]
my environment is：
GPU TITAN X (Pascal)
cuda 8.0
cudnn 6.0
python 2.7
torch 1.0.0
torchvision 0.2.1

command lines is： python main.py
The parameters are set by default.  Do you have any suggestions?

**Comment by jiangtaoxie** [comment]
@txiaoyun It seems no problem. Do you try `sh train.sh`? by the way, what is `run the second time`? you run it first, then `Ctrl+c` and run it again?

**Comment by txiaoyun** [comment]
For example, first I run mpncovresnet50, it runs successfully. and then i run mpncovresnet101, it will occur. But, when I reconnect to GPU, mpncovresnet101 will run successfully. 
Sometimes it happens, sometimes it doesn't.  And, after the first occurrence, subsequent runs will occur. Whichever program I run will appear. 

I try, it still appears.

**Comment by jiangtaoxie** [comment]
@txiaoyun Maybe it's system problem.
